runtime: python311  # Specify the Python version
entrypoint: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 main:app  # For a Flask socket io app

handlers:
- url: /.*
  script: auto
